apps/stores/urls.py
from django.urls import path
from django.conf.urls import url
from .views import *
from .models import *


urlpatterns = [
    path('', Test.as_view(), name='stores_view_url'),
    path('create/', StoreCreate.as_view(), name='store_create_url'),
    path('manage/', StoreManage.as_view(), name='store_manage_url'),

    url(r'\w*', Restaraunts.as_view(), name='store_view_individual'),

]

doublemaxdelivery/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('apps.orders.urls')),
    path('user/', include('apps.profiles.urls')),
    path('stores/', include('apps.stores.urls')),
    path('', include('apps.food_delivery.urls')),
    path('get_address/', include('apps.geocoder.urls')),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
        urlpatterns += staticfiles_urlpatterns()

apps/stores/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from apps.profiles.models import User
from apps.geocoder.models import Place
import time


def images_path(instance, filename):
    return get_current_timestamp() + '{0}'.format(filename)


def get_current_timestamp():
    time_st = time.gmtime(time.time())
    return time.strftime("%d%H%M%S", time_st)


class Store(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(max_length=40, unique=True)
    store_thumbnail = ProcessedImageField(upload_to=images_path, blank=True,
                                          processors=[ResizeToFill(250, 250)],
                                          format='JPEG',
                                          options={'quality': 60})
    main_place = models.ForeignKey(Place, on_delete=models.PROTECT,
                                   related_name='main_place', blank=False, default=None)
    places = models.ManyToManyField(Place, blank=True)
    admin = models.ForeignKey(User, on_delete=models.CASCADE, blank=False, default=None)

    def __str__(self):
        return self.name


class Email(models.Model):
    email = models.EmailField()
    stores = models.ManyToManyField(Store)


class Products(models.Model):
    name = models.CharField(max_length=40)
    products_thumbnail = ProcessedImageField(upload_to=images_path, blank=True,
                                             processors=[ResizeToFill(250, 250)],
                                             format='JPEG',
                                             options={'quality': 60})
    store_id = models.ForeignKey(Store, on_delete=models.CASCADE, blank=False, default=None)
    quantity = models.IntegerField()
    row = models.IntegerField()
    price = models.IntegerField()


class Phone(models.Model):
    phone = models.CharField(max_length=40)
    stores = models.ManyToManyField(Store)

apps/stores/forms.py
from django import forms
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from libs.Filters.filters import phone_number_filter
from .models import Store
from libs.Filters.filters import address_fullness_filter
import json


class StoreCreatingForm(forms.Form):
    widgets = {
        'name': forms.TextInput(attrs={'placeholder': 'store name'}),
        'slug': forms.TextInput(attrs={'placeholder': 'store short url'}),
        'store_thumbnail': forms.ClearableFileInput(attrs={'placeholder': 'store name'}),
        'email': forms.EmailInput(attrs={'placeholder': 'main email'}),
        'phone': forms.TextInput(attrs={'placeholder': 'main phone'}),
        'address': forms.TextInput(attrs={'placeholder': 'address'}),
    }

    name = forms.CharField(widget=widgets['name'], max_length=40)
    slug = forms.CharField(widget=widgets['slug'], max_length=40)
    email = forms.EmailField(widget=widgets['email'])
    phone = forms.CharField(widget=widgets['phone'], max_length=40)
    address = forms.CharField(widget=widgets['address'])
    store_thumbnail = forms.ImageField(widget=widgets['store_thumbnail'])

    def __init__(self, *args, **kwargs):

        super(StoreCreatingForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'dka-input input_placement'

    def clean_slug(self):
        new_slug = self.cleaned_data['slug']
        if new_slug != slugify(new_slug, allow_unicode=True):
            raise ValidationError('Slug is not correct, it may contain only letter and "-_" symbols')
        if Store.objects.filter(slug__iexact=new_slug):
            raise ValidationError('This slug exists, try to figure out the unique one')
        return new_slug

    def clean_phone(self):
        number = self.cleaned_data['phone']
        if phone_number_filter(number):
            return number
        else:
            raise ValidationError("Entered incorrect phone number")

    def clean_address(self):
        address = self.cleaned_data['address']

        cleaned_address = address_fullness_filter(address)

        if len(cleaned_address) < 3:
            raise ValidationError("Provide address with precision of building")

        info_json = json.dumps(cleaned_address)
        return info_json

apps/stores/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import View
from .forms import *
from .models import *
import json


class Test(View):
    def get(self, request):
        stores = Store.objects.all()
        return render(request, template_name='stores/stores.html', context={'stores': stores})


class Restaraunts(View):
    template = 'stores/restaurant.html'

    def get(self, request):
        store_slug = str(request).split('/')[-2]
        store = Store.objects.filter(slug=store_slug)
        if not store:
            return redirect('stores_view_url')
        store = store[0]
        products = Products.objects.filter(store_id=store.id)
        context = {
            'store': store,
            'products': products
        }

        return render(request, template_name=self.template, context=context)

    def post(self, request):
        pass


class StoreCreate(View):
    general_form_model = StoreCreatingForm
    template = 'stores/store_create.html'

    @method_decorator(login_required)
    def get(self, request):
        general_form = self.general_form_model
        context = {
            'general_form': general_form,
        }
        return render(request, template_name=self.template, context=context)

    @method_decorator(login_required)
    def post(self, request):
        bound_form = self.general_form_model(request.POST, request.FILES)
        if bound_form.is_valid():
            data = bound_form.cleaned_data
            address = json.loads(data['address'])
            email = Email(email=data['email'])
            phone = Phone(phone=data['phone'])
            place = Place(city=address['locality'],
                          street=address['street'],
                          building=address['house'])
            email.save()
            phone.save()
            place.save()
            store = Store(name=data['name'],
                          slug=data['slug'],
                          store_thumbnail=data['store_thumbnail'],
                          main_place=place,
                          admin=request.user)
            store.save()

            store.email_set.add(email)
            store.phone_set.add(phone)

            email.save()
            phone.save()
            store.save()
            place.save()
            return redirect('main_page_url')
        else:
            context = {
                'general_form': bound_form,
            }
            return render(request, template_name=self.template, context=context)


class StoreManage(View):

    def get(self, request):
        return render(request, template_name='stores/stores_manage.html')

    def post(self, request):
        pass

apps/stores/templates/stores/restaurant.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} {{ store.name }} menu
{% endblock %}

{% block page_title %}
    {{ block.super }} {{ store.name }} menu
{% endblock %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/restaurant.css' %}">
{% endblock %}

{% block content %}
    <div class="mainFrame">
        <div class="mainInfoFrame">
            <div class="avatarShop">
                <img src="{{ store.store_thumbnail.url }}">
            </div>
            <div class="infoShop">
              <div class="frameName">
                <p class="nameShop">{{ store.name }}</p>
               <div class=frameRating> <p class="nameShop" >4<i class="small material-icons" style="font-size:45px; padding-bottom: 2px; color: gold;">star</i></p></div>
              </div>
                <li class="divider" style="background-color: #340068;" tabindex="1"></li>
                <p class="description" style="font-size: 20px;">Понять ценностное предложение этого бренда совсем несложно. Чем один вид шоколада может отличаться от другого? M&M смогли выделить свой продукт на фоне конкурентов – их шоколад не тает в руках.</p>
                <p class="description address" ><i class=" small material-icons">location_on</i> {{ store.main_place }}</p>
            </div>
        </div>

        <div class="containerFood">
        <div class="frameFood">
                        {% for product in products %}

            <div class="cardFood">
                <div class="card hoverable" style="border-radius: 40px;">
                  <div class="card-image" style="border-radius: 40px;">

                    <img class="picFood" src="{% static 'img/sample-pasta-2.jpg' %}"  alt="Food" style="border-top-right-radius: 40px; border-top-left-radius: 40px;">

                    <a class="btn-floating halfway-fab waves-effect waves-light" style="background-color: #EF798A "><i class="material-icons">add</i></a>
                  </div>
                  <div class="card-content">
                    <span class="card-title">{{ product.name }}</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                  </div>
                  <p class="price">{{ product.price }}</p>
                </div>
              </div>
{% endfor %}

          <!--    <div class="cardFood">
                  <div class="card hoverable" style="border-radius: 40px;">
                    <div class="card-image" style="border-radius: 40px;">
                      <img class="picFood" src="{% static 'img/sample-pasta-2.jpg' %}"  alt="Food" style="border-top-right-radius: 40px; border-top-left-radius: 40px;">

                      <a class="btn-floating halfway-fab waves-effect waves-light" style="background-color: #EF798A "><i class="material-icons">add</i></a>
                    </div>
                    <div class="card-content">
                      <span class="card-title">{{ product.name }}</span>
                      <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                    </div>
                    <p class="price">{{ product.price }}</p>
                  </div>
                </div>
                <div class="cardFood">
                    <div class="card hoverable" style="border-radius: 40px;">
                      <div class="card-image" style="border-radius: 40px;">
                        <img class="picFood" src="{% static 'img/sample-pasta-2.jpg' %}"  alt="Food" style="border-top-right-radius: 40px; border-top-left-radius: 40px;">

                        <a class="btn-floating halfway-fab waves-effect waves-light" style="background-color: #EF798A "><i class="material-icons">add</i></a>
                      </div>
                      <div class="card-content">
                        <span class="card-title">{{ product.name }}</span>
                        <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                      </div>
                      <p class="price">{{ product.price }}</p>
                    </div>
                  </div>



          <div class="cardFood">
                <div class="card hoverable" style="border-radius: 40px;">
                  <div class="card-image" style="border-radius: 40px;">
                    <img class="picFood" src="{% static 'img/sample-pasta-2.jpg' %}"  alt="Food" style="border-top-right-radius: 40px; border-top-left-radius: 40px;">
                    
                    <a class="btn-floating halfway-fab waves-effect waves-light" style="background-color: #EF798A "><i class="material-icons">add</i></a>
                  </div>
                  <div class="card-content">
                    <span class="card-title">{{ product.name }}</span>
                    <p>I am a very simple card. I am good at containing small bits of information. I am convenient because I require little markup to use effectively.</p>
                  </div>
                  <p class="price">{{ product.price }}</p>
                </div>
              </div>
!-->
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js"></script>
    <script>
      $(document).ready(function(){
        $('.sidenav').sidenav();
        $('.materialboxed').materialbox();
        $('.parallax').parallax();
        $('.tabs').tabs();
      });
    </script>
    <script>
         $('.dropdown-trigger').dropdown({
  
    });
    </script>
    {% endblock %}
  </body>
</html>

apps/stores/templates/stores/store_create.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}


{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <script id="get_address_url" type="application/json">{"url": "{% url 'get_address_by_address_url' %}"}</script>
    <script src="{% static 'script/address_getter.js' %}" type="text/javascript"></script>
{% endblock %}

{% block title %}
    {{ block.super }} Store creating
{% endblock %}

{% block page_title %}
    {{ block.super }} Store creating
{% endblock %}


{% block content %}
    <div id="signUpFrame">
        <div id="signUpSubframe">
            <p id="signupText">Create store</p>
            <form enctype="multipart/form-data" action="{% url 'store_create_url' %}" method="post">
                {% csrf_token %}

                {% for field in general_form %}
                    {% if field.html_name != 'store_thumbnail' and field.html_name != 'address' %}
                        <div>
                            {% if field.errors %}
                                <div class='input_placement input_error'>
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <div>
                        {% if general_form.address.errors %}
                            <div class='input_placement input_error'>
                                {{ general_form.address.errors }}
                            </div>
                        {% endif %}
                        {{ general_form.address }}
                        <ul class="addressesList input_placement"></ul>
                    </div>
    

                <div class="input input_placement" id="app">
                    <div class="upload-btn-wrapper">
                        <button class="btn btn-submit">Upload an image</button>
                        <input type="file" style="height: 50px; width: 400px;"
                               name="store_thumbnail"
                               placeholder="store image"
                               accept="image/*"
                               onchange="previewFile()"
                               id="id_store_thumbnail"  v-on:click="upload()"/>
                    </div>
                    <img class="upImg" v-if="downloaded"  src="" height="200" alt="Image preview...">
                </div>
               
                <button type="submit" class="waves-effect waves-light signUpButton">SUBMIT</button>
            </form>
        </div>
    </div>
    <script src="https://unpkg.com/vue"></script>
    <script>
        var app = new Vue({
            el: '#app',
            data: {
                downloaded: false,
            },
            methods: {
                upload: function() {
                    this.downloaded = true;
                    console.log("uploaded");
                }
            },
        });
    </script>
    <script>
            function previewFile(){
                var preview = document.querySelector('img'); //selects the query named img
                var file    = document.querySelector('input[type=file]').files[0]; //sames as here
                var reader  = new FileReader();
         
                reader.onloadend = function () {
                    preview.src = reader.result;
                }
         
                if (file) {
                    reader.readAsDataURL(file); //reads the data as a URL
                } else {
                    preview.src = "";
                }
           }
         
           previewFile();  //calls the function named previewFile()
    </script>
{% endblock %}

apps/stores/templates/stores/stores.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} Stores
{% endblock %}

{% block page_title %}
    {{ block.super }} Stores
{% endblock %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/catalog.css' %}">
{% endblock %}

{% block content %}
    <div class="mainFrame">
        <div class="title">
            <p>Catalog</p>
        </div>
        <div class="contentBox">

            {% for store in stores %}
                <div class="rest_card">
                    <div class="storeLogo">
                        <a href="{{ store.slug }}/"> <img src="{{ store.store_thumbnail.url }}" alt="logo">
                       </a>
                    </div>
                    <div class="bla">
                        <div class="name_def">
                            <p class="name">

                                <a href="{{ store.slug }}/">{{ store.name }}</a>
                            </p>
                            <p class="def">
                                {{ store.main_place }}
                            </p>
                        </div>
                        <div class="rating">
                            <p class="num_of_star">
                                4
                            </p>
                            <img src="{% static '/icons/content/star.png' %}" class="star" alt="Stars">
                        </div>
                    </div>
                </div>
            {% endfor %}

        </div>
    </div>
{% endblock %}

apps/stores/templates/stores/stores_manage.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} Stores managing
{% endblock %}

{% block page_title %}
    {{ block.super }} Stores managing
{% endblock %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/catalog.css' %}">
{% endblock %}

{% block content %}
    <div class="mainFrame">
        <div class="title">
            <p>Your stores</p>
        </div>
        <div class="stores-box">
            <div class="card">
                <div class="card-image waves-effect waves-block waves-light">
                    <img class="activator" style="width: 256px; height: 256px"
                         src="{% static 'img/receiving-shipping-box-on-ipad.jpg' %}">
                </div>
                <div class="card-content">
                    <span class="card-title activator grey-text text-darken-4">Card Title<i
                            class="material-icons right">more_vert</i></span>
                    <p><a href="#">This is a link</a></p>
                </div>
                <div class="card-reveal">
                    <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
                    <p>Here is some more information about this product that is only revealed once clicked on.</p>
                </div>
            </div>

        </div>
    </div>
{% endblock %}