apps/profiles/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('sign_up/', UserCreate.as_view(), name='user_create_url'),
    path('login/', UserLogin.as_view(), name='user_login_url'),
    path('logout/', user_logout, name='user_logout_url'),
    path('edit/', UserEdit.as_view(), name='user_edit_url'),
    path('', UserProfile.as_view(), name='user_profile_url')
]

doublemaxdelivery/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/', include('apps.orders.urls')),
    path('user/', include('apps.profiles.urls')),
    path('stores/', include('apps.stores.urls')),
    path('', include('apps.food_delivery.urls')),
    path('get_address/', include('apps.geocoder.urls')),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)
        urlpatterns += staticfiles_urlpatterns()

apps/orders/models.py
from django.db import models
from apps.profiles.models import User
from apps.geocoder.models import Place


class Order(models.Model):
    PLACED = 'p'
    TAKEN = 't'
    DELIVERING = 'd'
    COMPLETED = 'c'

    orderID = models.AutoField(primary_key=True)
    date = models.DateTimeField(auto_now_add=True)
    store = models.CharField(max_length=150, default=None)
    store_address = models.ForeignKey(Place, related_name="store_address", default=None,
                                      blank=False, on_delete=models.CASCADE)
    destination_address = models.ForeignKey(Place, related_name="destination_address", default=None,
                                            blank=False, on_delete=models.CASCADE)
    product = models.CharField(max_length=2000)
    customer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="customer", default=None)
    courier = models.ForeignKey(User, on_delete=models.CASCADE, related_name="courier", default=None, null=True)
    status_choices = (
        (PLACED, 'Placed'),
        (TAKEN, 'Taken'),
        (DELIVERING, 'Delivering'),
        (COMPLETED, 'Completed')
    )
    status = models.CharField(max_length=1, choices=status_choices, default='p')

    def set_courier(self, courier_id):
        if courier_id:
            self.courier_id = courier_id
        else:
            raise ValueError("Courier are already assigned to this order")

    def __str__(self):
        return str(self.orderID) + ": " + str(self.destination_address)

apps/profiles/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager
from apps.geocoder.models import Place
from apps.geocoder.views import get_address_by_address


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
        )

        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, first_name, last_name, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            first_name=first_name,
            last_name=last_name,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    userID = models.AutoField(primary_key=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=150, default=None)
    last_name = models.CharField(max_length=150, default=None)
    phone = models.CharField(max_length=20)
    address = models.OneToOneField(Place, on_delete=models.CASCADE, blank=True, default=None)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_store_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.last_name + " " + self.first_name

    def is_staff(self):
        if self.is_admin:
            return True
        else:
            return False

    def has_perm(self, perm, obj=None):
        if self.is_admin:
            return True
        else:
            return False

    def has_module_perms(self, app_label):
        if self.is_admin:
            return True
        else:
            return False

apps/profiles/forms.py
from django import forms
from .models import *
from django.core.exceptions import ValidationError
from django.contrib.auth.password_validation import validate_password
from libs.Filters.filters import *


class UserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'placeholder': 'password'}))
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput(
        attrs={'placeholder': 'repeat password'}))
    address = forms.CharField(label="Address", widget=forms.TextInput(
        attrs={'placeholder': 'address'}))

    class Meta:
        model = User
        fields = ['email', 'password1', 'password2', 'first_name', 'last_name', 'phone']

        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'first name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'last name'}),
            'email': forms.TextInput(attrs={'placeholder': 'e-mail'}),
            'phone': forms.TextInput(attrs={'placeholder': 'phone'}),
        }

    def __init__(self, *args, **kwargs):

        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input input_placement'

    def clean_password2(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        validate_password(password=password2)

        return password2

    def clean_email(self):
        new_email = self.cleaned_data['email']

        if User.objects.filter(email__exact=new_email).count():
            raise ValidationError('This e-mail is already used')

        return new_email

    def clean_phone(self):
        number = self.cleaned_data['phone']
        if phone_number_filter(number):
            return number
        else:
            raise ValidationError("Entered incorrect phone number")

    def clean_address(self):
        address = self.cleaned_data['address']

        cleaned_address = address_fullness_filter(address)

        if len(cleaned_address) < 3:
            raise ValidationError("Provide address with precision of building")

        info_json = json.dumps(cleaned_address)
        return info_json

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password2'])
        if commit:
            user.save()
        return user


class UserLoginForm(forms.Form):
    email = forms.EmailField(label='E-mail', widget=forms.EmailInput(attrs={'class': 'dka-input',
                                                                            'placeholder': 'email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'dka-input',
                                                                                   'placeholder': 'password'}))


class UserEditForm(forms.Form):
    widgets = {
        'first_name': forms.TextInput(attrs={'style': "height: 30px; width: 90%;", 'class': "fullnameText"}),
        'last_name': forms.TextInput(attrs={'style': "height: 30px; width: 90%;", 'class': "fullnameText"}),
        'email': forms.EmailInput(attrs={'style': "height: 30px; width: 90%;", 'class': "emailText"}),
        'address': forms.TextInput(attrs={'style': "width: 90%; position: relative; left: 10px;"}),
    }

    first_name = forms.CharField(widget=widgets['first_name'], max_length=40)
    last_name = forms.CharField(widget=widgets['last_name'], max_length=40)
    email = forms.EmailField(widget=widgets['email'])
    address = forms.CharField(widget=widgets['address'])

    def clean_address(self):
        address = self.cleaned_data['address']

        cleaned_address = address_fullness_filter(address)

        if len(cleaned_address) < 3:
            raise ValidationError("Provide address with precision of building")

        info_json = json.dumps(cleaned_address)
        return info_json

    def clean_email(self):
        new_email = self.cleaned_data['email']
        print(self.changed_data)

        if 'email' in self.changed_data and User.objects.filter(email=new_email).count():
            raise ValidationError('This e-mail is already used')

        return new_email

apps/profiles/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect
from .forms import *
from apps.orders.models import Order
import json


class UserProfile(View):

    def get(self, request):
        orders_made = Order.objects.filter(customer_id__exact=request.user.userID)
        orders_delivered = Order.objects.filter(courier_id__exact=request.user.userID)
        context = {
            'orders_made': orders_made,
            'orders_delivered': orders_delivered,
            'orders_made_amount': len(orders_made),
            'orders_delivered_amount': len(orders_delivered),
            'user': request.user,
        }
        return render(request, template_name='profiles/user_profile.html', context=context)


def user_logout(request):
    logout(request)
    return redirect('main_page_url')


class UserLogin(View):

    def get(self, request):
        form = UserLoginForm()
        context = {
            'form': form,
        }
        return render(request, template_name='profiles/user_login.html', context=context)

    def post(self, request):
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('user_profile_url')
        else:
            context = {
                'form': UserLoginForm(request.POST)
            }
            return render(request, template_name='profiles/user_login.html', context=context)


class UserCreate(View):
    form_model = UserForm
    template = 'profiles/user_create.html'
    success_redirect_url = 'user_login_url'

    def get(self, request):
        form = self.form_model()
        get_address_url = 'get_address_by_address_url'
        context = {
            'form': form,
            'get_address_url': get_address_url,
        }
        return render(request, self.template, context=context)

    def post(self, request):
        bound_form = self.form_model(request.POST)
        if bound_form.is_valid():
            address_json = bound_form.cleaned_data['address']
            address_dict = json.loads(address_json)

            place = Place(city=address_dict['locality'], street=address_dict['street'], building=address_dict['house'])
            place.save()
            new_user = bound_form.save(commit=False)
            new_user.address = place
            new_user.save()
            return redirect(self.success_redirect_url)
        return render(request, self.template, context={'form': bound_form})


class UserEdit(View):
    form_model = UserEditForm
    template = 'profiles/user_edit.html'
    success_redirect_url = 'user_profile_url'

    def get(self, request):
        data = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'address': request.user.address.display_full
        }
        form = self.form_model(initial=data)
        context = {
            'form': form
        }
        return render(request, template_name=self.template, context=context)

    def post(self, request):
        data = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.email,
            'address': request.user.address.display_full
        }
        bound_form = self.form_model(request.POST, initial=data)
        if bound_form.is_valid():
            user = request.user
            place = user.address

            address_json = bound_form.cleaned_data['address']
            address = json.loads(address_json)

            place.city = address['locality']
            place.street = address['street']
            place.building = address['house']
            place.save()

            user.first_name = bound_form.cleaned_data['first_name']
            user.last_name = bound_form.cleaned_data['last_name']
            user.email = bound_form.cleaned_data['email']
            user.save()

            return redirect(self.success_redirect_url)
        return render(request, self.template, context={'form': bound_form})

apps/profiles/templates/profiles/user_create.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}


{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <script id="get_address_url" type="application/json">{"url": "{% url 'get_address_by_address_url' %}"}</script>
    <script src="{% static 'script/address_getter.js' %}" type="text/javascript"></script>
{% endblock %}

{% block title %}
    {{ block.super }} Sign user
{% endblock %}

{% block page_title %}
    {{ block.super }} Sign user
{% endblock %}


{% block content %}
    <div id="signUpFrame">
        <div id="signUpSubframe">
            <p id="signupText">Sign Up</p>
            <form action="{% url 'user_create_url' %}" method="post">
                {% csrf_token %}

                {% for field in form %}
                    {% if field.html_name != 'address' %}
                        <div>
                            {% if field.errors %}
                                <div class='input_placement input_error'>
                                    {{ field.errors }}
                                </div>
                            {% endif %}

                            {{ field }}
                        </div>
                    {% endif %}
                {% endfor %}

                <div>
                    {% if form.address.errors %}
                        <div>
                            {{ form.address.errors }}
                        </div>
                    {% endif %}
                    {{ form.address }}
                    <ul class="addressesList input_placement"></ul>
                </div>

                <button type="submit" class="waves-effect waves-light signUpButton">SUBMIT</button>
            </form>

        </div>
    </div>
{% endblock %}

apps/profiles/templates/profiles/user_edit.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} User edit
{% endblock %}

{% block page_title %}
    {{ block.super }} User edit
{% endblock %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/toggle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
    <script id="get_address_url" type="application/json">{"url": "{% url 'get_address_by_address_url' %}"}</script>
    <script src="{% static 'script/address_getter.js' %}" type="text/javascript"></script>
{% endblock %}

{% block content %}
    <form action="{% url 'user_edit_url' %}" method="post">
        {% csrf_token %}
        <div class="mainFrame" id="app">
            <div class="mainInfoFrame">

                <div class="fullnameFrame">
                    <div class="userPicEllipse">
                        <div class="userPicHead"></div>
                        <div class="userPicBody"></div>
                    </div>

                    <div class="fullnameTextFrame">
                        {{ form.first_name }}
                        {{ form.last_name }}
                        {{ form.email }}
                        <p class="telegramLink"></p>
                    </div>
                </div>
                <div class="addressFrame">
                    <p class="addressTitle">Address</p>
                    {{ form.address }}
                    <ul class="addressesList" style="width: 93%; position: relative; left: 10px;"></ul>
                </div>
                <div class="cardFrame">
                    <p class="bankName">
                        <input type="text" style="height: 27px; width: 60%;"
                               name="bank_name" value="Bank"/>
                    </p>
                    <input type="text" class="cardNumber"
                           style="left: 20px; width: 80%; height: 27px; margin: 0; color: black; "
                           name="bankcard_number" value="1234 5678 9098 7654"/>
                    <p class="cardDate">
                        <input style="float:left; width: 20%; height: 22px; margin: 0 0 0 60px;"
                               name="bankcard_expiry_date" type="text" value="12/19"/>
                    </p>
                    <p class="cardHolder">
                        <input style="float:left; width: 80%; height: 22px; margin: 0;" type="text"
                               name="bankcard_holder_name" value="RINAT MULLALA"/>
                    </p>
                </div>
            </div>

            <div class="profile-edit-errors">
                {% for field in form %}
                    {% if field.errors %}
                        <div>
                            {{ field.html_name }}
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
            </div>

            <button type="submit" class="waves-effect waves-light signUpButton">SUBMIT</button>

        </div>

    </form>
{% endblock %}

apps/profiles/templates/profiles/user_login.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/signup.css' %}">
{% endblock %}

{% block title %}
    {{ block.super }} Login
{% endblock %}

{% block page_title %}
    {{ block.super }} Login
{% endblock %}

{% block content %}
    <div id="authFrame">
        <div class="authText authHeader">
            Auth
        </div>

        <div class="authPaintFrame">
            <div class="authPaintEllipse">
                <div id="authPaintHead">
                    <div id="authPaintBody">
                    </div>
                </div>
            </div>
        </div>
        <form action="{% url 'user_login_url' %}" method="post">
            {% csrf_token %}

            {% for field in form %}
                <div>
                    {% if field.errors %}
                        <div>
                            {{ field.errors }}
                        </div>
                    {% endif %}

                    {{ field }}
                </div>
            {% endfor %}

            <div class="authButtonWrapper">
                <button type="submit" class="waves-effect waves-light authButton">Sign in</button>
            </div>


        </form>
        <a href="{% url 'user_create_url' %}" class="authSignUpLink">Create an Account?</a>
    </div>

{% endblock %}

apps/profiles/templates/profiles/user_profile.html
{% extends 'food_delivery/food_delivery_base.html' %}
{% load static %}

{% block title %}
    {{ block.super }} Profile
{% endblock %}

{% block page_title %}
    {{ block.super }} Profile
{% endblock %}

{% block external_js_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/toggle.css' %}">

{% endblock %}

{% block content %}
    <div class="mainFrame" id="app">
        <div class="mainInfoFrame">

            <div class="fullnameFrame">
                <div class="userPicEllipse">
                    <div class="userPicHead"></div>
                    <div class="userPicBody"></div>
                </div>

                <div class="fullnameTextFrame">
                    <p class="fullnameText">{{ user }}</p>
                    <p class="emailText">{{ user.email }}</p>
                    <p class="telegramLink"></p>
                </div>
            </div>
            <div class="addressFrame">
                <p class="addressTitle">Address</p>
                <p class="addressText">{{ user.address.city }}</p>
                <p class="addressText">{{ user.address.street }}</p>
                <p class="addressText">{{ user.address.building }}</p>
            </div>
            <div class="cardFrame">
                <p class="bankName">Tinkoff</p>
                <p class="cardNumber">1234 5678 9098 7654</p>
                <p class="cardDate">12/19</p>
                <p class="cardHolder">RINAT MULLALA</p>
            </div>
        </div>
        <div class="toggleFrame">
            <label class="dka-toggler dka-toggler--is-active" id="dka-filt-css">Customer</label>
            <div class="dka-toggle">
                <input type="checkbox" id="dka-switcher" class="dka-check" v-on:click="dkaSwitcher()">
                <b class="dka-b dka-switch"></b>
            </div>
            <label class="dka-toggler" id="dka-filt-javascript">Courier</label>
        </div>
        <div class="ordersInfoFrame">
            <transition name="customer">
                <div class="ordersInfoPlate" v-if="customer" style="float: left;">
                    <div class="orderInfo">
                        <div class="orderInfoTextFrame">
                            <p class="orderInfoTextName">Rating:<a class="orderInfoTextValue">Soon</a></p>
                            <p class="orderInfoTextName">Reviews:<a class="orderInfoTextValue">Soon</a></p>
                            <p class="orderInfoTextName">Orders:<a
                                    class="orderInfoTextValue">{{ orders_made_amount }}</a>
                            </p>
                            <p class="orderInfoTextName">Orders in progress:<a
                                    class="orderInfoTextValue">{{ orders_delivered_amount }}</a></p>
                        </div>
                    </div>
                    <div class="ordersListFrame">
                        {% for order in orders_made %}
                            <div class="orderFrame">
                                <p class="orderFrameId">#{{ order.orderID }}</p>
                                <p class="orderFrameStatus">{{ order.get_status_display }}</p>
                                <p class="orderFrameName">{{ order.store_address }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </transition>

            <transition name="courier">
                <div class="ordersInfoPlate" v-if="courier">
                    <div class="orderInfo">
                        <div class="orderInfoTextFrame">
                            <p class="orderInfoTextName">Rating:<a class="orderInfoTextValue">Soon</a></p>
                            <p class="orderInfoTextName">Reviews:<a class="orderInfoTextValue">Soon</a></p>
                            <p class="orderInfoTextName">Orders:<a
                                    class="orderInfoTextValue">{{ orders_delivered_amount }}</a>
                            </p>
                            <p class="orderInfoTextName">Orders in progress:<a
                                    class="orderInfoTextValue">{{ orders_delivered_amount }}</a></p>
                        </div>
                    </div>
                    <div class="ordersListFrame">
                        {% for order in orders_delivered %}
                            <div class="orderFrame">
                                <p class="orderFrameId">#{{ order.orderID }}</p>
                                <p class="orderFrameStatus">{{ order.get_status_display }}</p>
                                <p class="orderFrameName">{{ order.destination_address }}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </transition>
        </div>
    </div>



    <script src="https://unpkg.com/vue"></script>
    <script src="{% static 'script/profile.vue' %}"></script>
    <script>
        const e = document.getElementById("dka-filt-css"),
            d = document.getElementById("dka-filt-javascript"),
            t = document.getElementById("dka-switcher");

        e.addEventListener("click", function () {
            t.checked = false;
            e.classList.add("dka-toggler--is-active");
            d.classList.remove("dka-toggler--is-active");
        });

        d.addEventListener("click", function () {
            t.checked = true;
            d.classList.add("dka-toggler--is-active");
            e.classList.remove("dka-toggler--is-active");
        });

        t.addEventListener("click", function () {
            d.classList.toggle("dka-toggler--is-active");
            e.classList.toggle("dka-toggler--is-active");
        })
    </script>


{% endblock %}